import {
  agentConversationCredentialsBodySchema,
  agentConversationCredentialsPathSchema,
  agentConversationCredentialsResponseSchema,
  agentCredentialOptionsQuerySchema,
  agentCredentialOptionsSchema,
  agentSessionIdentitySchema,
  awsCredentialsSchema,
  cloudflareCredentialsSchema,
  gcpCredentialsSchema,
  tailscaleCredentialsSchema,
} from './agent-schemas'
import {
  agentSessionAwsAccountPathSchema,
  agentSessionCloudflareAccountPathSchema,
  agentSessionGcpProjectPathSchema,
  agentSessionPathSchema,
  agentSessionTailscaleClientPathSchema,
  awsAccountPathSchema,
  awsCredentialQuerySchema,
  cloudflareAccountPathSchema,
  gcpCloudRunServiceApiPathSchema,
  gcpCredentialQuerySchema,
  gcpProjectPathSchema,
  tailscaleClientPathSchema,
} from './paths'
import {
  cloudRunRevisionsResponseSchema,
  cloudRunServiceSchema,
  cloudRunServicesResponseSchema,
} from './provider-schemas'

import type { ApiOperation } from '../registry'

export const agentCredentialOperations = [
  {
    operationId: 'agent.credentialOptions',
    method: 'get',
    path: '/agent/credential-options',
    tags: ['Agent credentials'],
    summary: 'List selectable agent credentials',
    description:
      'List AWS roles and GCP service accounts the current user can enable for an agent session.',
    auth: 'bearer',
    querySchema: agentCredentialOptionsQuerySchema,
    responseSchema: agentCredentialOptionsSchema,
  },
  {
    operationId: 'agent.conversationCredentials.update',
    method: 'patch',
    path: '/agent/conversations/{sessionId}/credentials',
    tags: ['Agent credentials'],
    summary: 'Update conversation credentials',
    description:
      'Persist the AWS roles and GCP service accounts enabled for an agent conversation.',
    auth: 'bearer',
    pathSchema: agentConversationCredentialsPathSchema,
    requestSchema: agentConversationCredentialsBodySchema,
    responseSchema: agentConversationCredentialsResponseSchema,
  },
  {
    operationId: 'agentSessions.get',
    method: 'get',
    path: '/agent-sessions/{sessionId}',
    tags: ['Agent sessions'],
    summary: 'Get agent session identity',
    description: 'Verify an agent session token and return its subject identity.',
    auth: 'bearer',
    pathSchema: agentSessionPathSchema,
    responseSchema: agentSessionIdentitySchema,
  },
  {
    operationId: 'agentSessions.awsCredentials.get',
    method: 'get',
    path: '/agent-sessions/{sessionId}/teams/{teamId}/aws-accounts/{accountId}/credentials',
    tags: ['Agent sessions', 'AWS credentials'],
    summary: 'Mint AWS credentials for an agent session',
    description:
      'Return short-lived AWS credentials for a selected AWS role enabled on the agent session.',
    auth: 'bearer',
    pathSchema: agentSessionAwsAccountPathSchema,
    querySchema: awsCredentialQuerySchema,
    responseSchema: awsCredentialsSchema,
  },
  {
    operationId: 'agentSessions.gcpCredentials.get',
    method: 'get',
    path: '/agent-sessions/{sessionId}/teams/{teamId}/gcp-projects/{projectId}/credentials',
    tags: ['Agent sessions', 'GCP credentials'],
    summary: 'Mint GCP credentials for an agent session',
    description:
      'Return a short-lived GCP access token for a selected GCP service account enabled on the agent session.',
    auth: 'bearer',
    pathSchema: agentSessionGcpProjectPathSchema,
    querySchema: gcpCredentialQuerySchema,
    responseSchema: gcpCredentialsSchema,
  },
  {
    operationId: 'agentSessions.cloudflareCredentials.get',
    method: 'get',
    path: '/agent-sessions/{sessionId}/teams/{teamId}/cloudflare-accounts/{accountId}/credentials',
    tags: ['Agent sessions', 'Cloudflare credentials'],
    summary: 'Fetch Cloudflare credentials for an agent session',
    description: 'Return the Cloudflare API token for a Cloudflare account bound to the team.',
    auth: 'bearer',
    pathSchema: agentSessionCloudflareAccountPathSchema,
    responseSchema: cloudflareCredentialsSchema,
  },
  {
    operationId: 'agentSessions.tailscaleCredentials.get',
    method: 'get',
    path: '/agent-sessions/{sessionId}/teams/{teamId}/tailscale-clients/{clientId}/credentials',
    tags: ['Agent sessions', 'Tailscale credentials'],
    summary: 'Mint Tailscale credentials for an agent session',
    description:
      'Return a short-lived Tailscale OAuth access token for a selected Tailscale OAuth client enabled on the agent session.',
    auth: 'bearer',
    pathSchema: agentSessionTailscaleClientPathSchema,
    responseSchema: tailscaleCredentialsSchema,
  },
  {
    operationId: 'teams.awsCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/aws-accounts/{accountId}/credentials',
    tags: ['AWS credentials'],
    summary: 'Mint AWS credentials',
    description:
      'Return short-lived AWS credentials for a team-bound AWS role. Agent sandboxes should prefer the agent-session-scoped path.',
    auth: 'bearer',
    pathSchema: awsAccountPathSchema,
    querySchema: awsCredentialQuerySchema,
    responseSchema: awsCredentialsSchema,
  },
  {
    operationId: 'teams.gcpCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/gcp-projects/{projectId}/credentials',
    tags: ['GCP credentials'],
    summary: 'Mint GCP credentials',
    description:
      'Return a short-lived GCP access token for a team-bound service account. Agent sandboxes should prefer the agent-session-scoped path.',
    auth: 'bearer',
    pathSchema: gcpProjectPathSchema,
    querySchema: gcpCredentialQuerySchema,
    responseSchema: gcpCredentialsSchema,
  },
  {
    operationId: 'teams.cloudflareCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/cloudflare-accounts/{accountId}/credentials',
    tags: ['Cloudflare credentials'],
    summary: 'Fetch Cloudflare credentials',
    description: 'Return the Cloudflare API token for a Cloudflare account bound to the team.',
    auth: 'bearer',
    pathSchema: cloudflareAccountPathSchema,
    responseSchema: cloudflareCredentialsSchema,
  },
  {
    operationId: 'teams.tailscaleCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/tailscale-clients/{clientId}/credentials',
    tags: ['Tailscale credentials'],
    summary: 'Mint Tailscale credentials',
    description:
      'Return a short-lived Tailscale OAuth access token for a team-bound OAuth client. Agent sandboxes should prefer the agent-session-scoped path.',
    auth: 'bearer',
    pathSchema: tailscaleClientPathSchema,
    responseSchema: tailscaleCredentialsSchema,
  },
  {
    operationId: 'teams.gcpCloudRunServices.list',
    method: 'get',
    path: '/teams/{teamId}/gcp-projects/{projectId}/cloud-run-services',
    tags: ['GCP Cloud Run'],
    summary: 'List Cloud Run services',
    description: 'List Cloud Run services in a team-bound GCP project.',
    auth: 'bearer',
    pathSchema: gcpProjectPathSchema,
    querySchema: gcpCredentialQuerySchema,
    responseSchema: cloudRunServicesResponseSchema,
  },
  {
    operationId: 'teams.gcpCloudRunServices.get',
    method: 'get',
    path: '/teams/{teamId}/gcp-projects/{projectId}/cloud-run-services/{region}/{name}',
    tags: ['GCP Cloud Run'],
    summary: 'Get a Cloud Run service',
    description: 'Fetch details for one Cloud Run service in a team-bound GCP project.',
    auth: 'bearer',
    pathSchema: gcpCloudRunServiceApiPathSchema,
    querySchema: gcpCredentialQuerySchema,
    responseSchema: cloudRunServiceSchema,
  },
  {
    operationId: 'teams.gcpCloudRunRevisions.list',
    method: 'get',
    path: '/teams/{teamId}/gcp-projects/{projectId}/cloud-run-services/{region}/{name}/revisions',
    tags: ['GCP Cloud Run'],
    summary: 'List Cloud Run revisions',
    description: 'List revisions for one Cloud Run service in a team-bound GCP project.',
    auth: 'bearer',
    pathSchema: gcpCloudRunServiceApiPathSchema,
    querySchema: gcpCredentialQuerySchema,
    responseSchema: cloudRunRevisionsResponseSchema,
  },
] as const satisfies readonly ApiOperation[]
