import {
  aliyunAccountPathSchema,
  aliyunClustersResponseSchema,
  aliyunCredentialsSchema,
  aliyunEcsResponseSchema,
  aliyunSwasResponseSchema,
  huaweiAccountPathSchema,
  huaweiCredentialsSchema,
  tencentAccountPathSchema,
  tencentClustersResponseSchema,
  tencentCredentialsSchema,
  volcengineAccountPathSchema,
  volcengineClustersResponseSchema,
  volcengineCredentialsSchema,
  volcengineEcsResponseSchema,
} from './cn-provider-schemas'
import {
  hetznerAccountPathSchema,
  linodeAccountPathSchema,
  tailscaleClientPathSchema,
  teamPathSchema,
} from './paths'
import {
  hetznerAccountsResponseSchema,
  hetznerCredentialsSchema,
  hetznerServersResponseSchema,
  linodeAccountsResponseSchema,
  linodeInstancesResponseSchema,
  lkeClustersResponseSchema,
  tailscaleClientsResponseSchema,
  tailscaleDevicesResponseSchema,
} from './provider-schemas'

import type { ApiOperation } from '../registry'

export const infraCredentialOperations = [
  {
    operationId: 'teams.linodeAccounts.list',
    method: 'get',
    path: '/teams/{teamId}/linode-accounts',
    tags: ['Linode accounts'],
    summary: 'List bound Linode accounts',
    description:
      'List Linode accounts connected to a Nuphos team without returning raw Linode tokens.',
    auth: 'bearer',
    pathSchema: teamPathSchema,
    responseSchema: linodeAccountsResponseSchema,
  },
  {
    operationId: 'teams.linodeInstances.list',
    method: 'get',
    path: '/teams/{teamId}/linode-accounts/{accountId}/instances',
    tags: ['Linode accounts'],
    summary: 'List Linode instances',
    description:
      'List Linode instances for a bound Linode account through Nuphos, without exposing the underlying Linode token.',
    auth: 'bearer',
    pathSchema: linodeAccountPathSchema,
    responseSchema: linodeInstancesResponseSchema,
  },
  {
    operationId: 'teams.linodeLkeClusters.list',
    method: 'get',
    path: '/teams/{teamId}/linode-accounts/{accountId}/lke-clusters',
    tags: ['Linode accounts'],
    summary: 'List LKE clusters',
    description:
      'List Linode Kubernetes Engine clusters for a bound Linode account through Nuphos.',
    auth: 'bearer',
    pathSchema: linodeAccountPathSchema,
    responseSchema: lkeClustersResponseSchema,
  },
  {
    operationId: 'teams.hetznerAccounts.list',
    method: 'get',
    path: '/teams/{teamId}/hetzner-accounts',
    tags: ['Hetzner accounts'],
    summary: 'List bound Hetzner accounts',
    description:
      'List Hetzner Cloud accounts connected to a Nuphos team without returning raw Hetzner API tokens.',
    auth: 'bearer',
    pathSchema: teamPathSchema,
    responseSchema: hetznerAccountsResponseSchema,
  },
  {
    operationId: 'teams.hetznerCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/hetzner-accounts/{accountId}/credentials',
    tags: ['Hetzner accounts'],
    summary: 'Fetch Hetzner credentials',
    description:
      'Return the Hetzner Cloud API token for an account bound to the team (used by the hcloud CLI in agent sandboxes).',
    auth: 'bearer',
    pathSchema: hetznerAccountPathSchema,
    responseSchema: hetznerCredentialsSchema,
  },
  {
    operationId: 'teams.hetznerServers.list',
    method: 'get',
    path: '/teams/{teamId}/hetzner-accounts/{accountId}/servers',
    tags: ['Hetzner accounts'],
    summary: 'List Hetzner servers',
    description:
      'List Hetzner Cloud servers for a bound Hetzner account through Nuphos, without exposing the underlying Hetzner API token.',
    auth: 'bearer',
    pathSchema: hetznerAccountPathSchema,
    responseSchema: hetznerServersResponseSchema,
  },
  {
    operationId: 'teams.tailscaleClients.list',
    method: 'get',
    path: '/teams/{teamId}/tailscale-clients',
    tags: ['Tailscale clients'],
    summary: 'List bound Tailscale OAuth clients',
    description:
      'List Tailscale OAuth clients connected to a Nuphos team without returning raw client secrets.',
    auth: 'bearer',
    pathSchema: teamPathSchema,
    responseSchema: tailscaleClientsResponseSchema,
  },
  {
    operationId: 'teams.tailscaleDevices.list',
    method: 'get',
    path: '/teams/{teamId}/tailscale-clients/{clientId}/devices',
    tags: ['Tailscale clients'],
    summary: 'List Tailscale devices',
    description: 'List devices in the tailnet associated with a bound Tailscale OAuth client.',
    auth: 'bearer',
    pathSchema: tailscaleClientPathSchema,
    responseSchema: tailscaleDevicesResponseSchema,
  },
  {
    operationId: 'teams.tencentCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/tencent-accounts/{accountId}/credentials',
    tags: ['Tencent accounts'],
    summary: 'Fetch Tencent credentials',
    description:
      'Return short-lived Tencent STS credentials (assumed-role secretId/secretKey + token) for a Tencent account bound to the team (used by tccli in agent sandboxes).',
    auth: 'bearer',
    pathSchema: tencentAccountPathSchema,
    responseSchema: tencentCredentialsSchema,
  },
  {
    operationId: 'teams.tencentClusters.list',
    method: 'get',
    path: '/teams/{teamId}/tencent-accounts/{accountId}/clusters',
    tags: ['Tencent accounts'],
    summary: 'List TKE clusters',
    description:
      'List Tencent Kubernetes Engine clusters for a bound Tencent account through Nuphos.',
    auth: 'bearer',
    pathSchema: tencentAccountPathSchema,
    responseSchema: tencentClustersResponseSchema,
  },
  {
    operationId: 'teams.aliyunCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/aliyun-accounts/{accountId}/credentials',
    tags: ['Alibaba Cloud accounts'],
    summary: 'Fetch Alibaba Cloud credentials',
    description:
      'Return short-lived Alibaba Cloud STS credentials (assumed-role AccessKeyId/AccessKeySecret + securityToken) for an account bound to the team (used by the aliyun CLI in agent sandboxes).',
    auth: 'bearer',
    pathSchema: aliyunAccountPathSchema,
    responseSchema: aliyunCredentialsSchema,
  },
  {
    operationId: 'teams.aliyunClusters.list',
    method: 'get',
    path: '/teams/{teamId}/aliyun-accounts/{accountId}/clusters',
    tags: ['Alibaba Cloud accounts'],
    summary: 'List ACK clusters',
    description:
      'List Alibaba Cloud Container Service (ACK) clusters for a bound Alibaba Cloud account through Nuphos.',
    auth: 'bearer',
    pathSchema: aliyunAccountPathSchema,
    responseSchema: aliyunClustersResponseSchema,
  },
  {
    operationId: 'teams.aliyunEcsInstances.list',
    method: 'get',
    path: '/teams/{teamId}/aliyun-accounts/{accountId}/ecs-instances',
    tags: ['Alibaba Cloud accounts'],
    summary: 'List ECS instances',
    description:
      'List Alibaba Cloud ECS instances for a bound Alibaba Cloud account through Nuphos.',
    auth: 'bearer',
    pathSchema: aliyunAccountPathSchema,
    responseSchema: aliyunEcsResponseSchema,
  },
  {
    operationId: 'teams.aliyunSwasInstances.list',
    method: 'get',
    path: '/teams/{teamId}/aliyun-accounts/{accountId}/swas-instances',
    tags: ['Alibaba Cloud accounts'],
    summary: 'List Simple Application Server instances',
    description:
      'List Alibaba Cloud Simple Application Server (SWAS) instances for a bound Alibaba Cloud account through Nuphos.',
    auth: 'bearer',
    pathSchema: aliyunAccountPathSchema,
    responseSchema: aliyunSwasResponseSchema,
  },
  {
    operationId: 'teams.volcengineCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/volcengine-accounts/{accountId}/credentials',
    tags: ['Volcengine accounts'],
    summary: 'Get Volcengine credentials',
    description:
      "Return the team's own Volcengine IAM AccessKeyId/SecretAccessKey for a bound Volcengine account (for the ve CLI in the agent sandbox).",
    auth: 'bearer',
    pathSchema: volcengineAccountPathSchema,
    responseSchema: volcengineCredentialsSchema,
  },
  {
    operationId: 'teams.volcengineClusters.list',
    method: 'get',
    path: '/teams/{teamId}/volcengine-accounts/{accountId}/clusters',
    tags: ['Volcengine accounts'],
    summary: 'List VKE clusters',
    description:
      'List Volcengine Kubernetes Engine (VKE) clusters for a bound Volcengine account through Nuphos.',
    auth: 'bearer',
    pathSchema: volcengineAccountPathSchema,
    responseSchema: volcengineClustersResponseSchema,
  },
  {
    operationId: 'teams.volcengineEcsInstances.list',
    method: 'get',
    path: '/teams/{teamId}/volcengine-accounts/{accountId}/ecs-instances',
    tags: ['Volcengine accounts'],
    summary: 'List ECS instances',
    description: 'List Volcengine ECS instances for a bound Volcengine account through Nuphos.',
    auth: 'bearer',
    pathSchema: volcengineAccountPathSchema,
    responseSchema: volcengineEcsResponseSchema,
  },
  {
    operationId: 'teams.huaweiCredentials.get',
    method: 'get',
    path: '/teams/{teamId}/huawei-accounts/{accountId}/credentials',
    tags: ['Huawei Cloud accounts'],
    summary: 'Get Huawei Cloud credentials',
    description:
      "Return short-lived federated AK/SK + security token for a bound Huawei Cloud account (for the huawei skill's hw-api.py signer and Huawei's SDKs).",
    auth: 'bearer',
    pathSchema: huaweiAccountPathSchema,
    responseSchema: huaweiCredentialsSchema,
  },
] as const satisfies readonly ApiOperation[]
