// Known read-only / inspect-only binaries. Every top-level segment must start
// with one of these (or a harmless builtin) for readOnly to hold.
export const READ_ONLY_BINARIES = new Set<string>([
  'ls',
  'cat',
  'echo',
  'pwd',
  'printf',
  'head',
  'tail',
  'wc',
  'grep',
  'egrep',
  'fgrep',
  'find',
  'stat',
  'file',
  'which',
  'type',
  'whoami',
  'id',
  'date',
  'env',
  'printenv',
  'df',
  'du',
  'ps',
  'top',
  'uptime',
  'uname',
  'hostname',
  'dig',
  'nslookup',
  'host',
  'ping',
  'curl',
  'wget',
  'jq',
  'yq',
  'awk',
  'sed',
  'sort',
  'uniq',
  'cut',
  'tr',
  'column',
  'diff',
  'cmp',
  'md5sum',
  'sha256sum',
  'base64',
  'xxd',
  'less',
  'more',
  'tree',
  'realpath',
  'basename',
  'dirname',
  'readlink',
  'test',
  'true',
  'false',
  'sleep',
  'seq',
  'kubectl',
  'aws',
  'gcloud',
  'helm',
  'gh',
  'git',
  'docker',
  'kubectx',
  'kubens',
  'argocd',
  'flux',
  'terraform',
  'psql',
  'mysql',
  'redis-cli',
  'mongosh',
  // Host inspection, the bread and butter of on-prem diagnostics over ssh.
  // systemctl earns its place only through the verb table below; its mutating
  // verbs (start/stop/restart/enable/disable) are already in MUTATING_TOKENS.
  // `mount` and `dmesg` are deliberately absent: both have mutating forms
  // (mounting a device, `dmesg -C`) that read like inspection at a glance.
  'systemctl',
  'journalctl',
  'free',
  'vmstat',
  'iostat',
  'lsblk',
  'ss',
  'netstat',
])

// Mutating tokens that, if present ANYWHERE in a read-candidate segment,
// disqualify the read-only fast-path — defense-in-depth over the per-CLI verb
// allowlist, catching sub-subcommands like `kubectl config set`,
// `git branch -D`, `gh workflow run`, `helm repo add`, `terraform state rm`,
// `argocd app sync`. Conservative by design: a false hit just sends the
// command to the judge, never the reverse.
export const MUTATING_TOKENS = new Set<string>([
  'set',
  'set-context',
  'set-cluster',
  'set-credentials',
  'use-context',
  'add',
  'create',
  'delete',
  'remove',
  'rm',
  'apply',
  'edit',
  'patch',
  'replace',
  'annotate',
  'label',
  'install',
  'uninstall',
  'upgrade',
  'rollback',
  'sync',
  'run',
  'trigger',
  'dispatch',
  'push',
  'commit',
  'merge',
  'rebase',
  'destroy',
  'import',
  'taint',
  'untaint',
  'mv',
  'cp',
  'write',
  'put',
  'update',
  'enable',
  'disable',
  'start',
  'stop',
  'restart',
  'scale',
  'rollout',
  'drain',
  'cordon',
  'uncordon',
  'expose',
  'expire',
  'rotate',
  'grant',
  'revoke',
  'attach',
  'detach',
  'associate',
  'disassociate',
  'reset',
])

// Per-CLI subcommands/verbs that are read-only. If a segment's binary is one of
// these CLIs, its verb must be in this set for the segment to count read-only.
// Only unambiguously read-only top-level verbs. Verbs with mutating
// sub-subcommands (kubectl config set, git branch -D, gh workflow run,
// helm repo add, terraform state rm, argocd app sync, git remote add) are
// deliberately OMITTED so they fall through to the judge; the MUTATING_TOKENS
// scan is a second net for any that slip in.
export const READ_ONLY_VERBS: Record<string, Set<string>> = {
  kubectl: new Set([
    'get',
    'describe',
    'logs',
    'top',
    'explain',
    'api-resources',
    'api-versions',
    'version',
    'cluster-info',
    'events',
  ]),
  aws: new Set(['describe', 'list', 'get', 'ls']), // matched loosely below (aws <svc> <verb>)
  gcloud: new Set(['describe', 'list', 'get']),
  helm: new Set([
    'list',
    'ls',
    'status',
    'get',
    'history',
    'show',
    'search',
    'version',
    'template',
    'lint',
  ]),
  gh: new Set(['browse', 'search', 'status']), // gh <cmd> is too mixed; only unambiguous reads
  git: new Set([
    'status',
    'log',
    'diff',
    'show',
    'rev-parse',
    'describe',
    'blame',
    'ls-files',
    'ls-remote',
    'cat-file',
    'reflog',
  ]),
  docker: new Set([
    'ps',
    'images',
    'logs',
    'inspect',
    'version',
    'info',
    'stats',
    'top',
    'port',
    'history',
  ]),
  argocd: new Set(['version']),
  flux: new Set(['get', 'logs', 'stat', 'version', 'tree', 'events']),
  terraform: new Set(['plan', 'show', 'output', 'validate', 'version', 'fmt', 'providers']),
  systemctl: new Set([
    'status',
    'show',
    'cat',
    'is-active',
    'is-enabled',
    'is-failed',
    'list-units',
    'list-unit-files',
    'list-timers',
    'list-sockets',
    'get-default',
    'show-environment',
  ]),
}
