#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  printf 'usage: inspect-project.sh TEAM_ID ZEABUR_ID PROJECT_ID\n' >&2
  exit 2
fi

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
team_id=$1
zeabur_id=$2
project_id=$3

bash "$script_dir/setup-credentials.sh" "$team_id" "$zeabur_id" >/dev/null
# shellcheck disable=SC1090 -- generated by the sibling setup script.
source "$HOME/.zeabur/nuphos.env"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT
chmod 700 "$tmp_dir"
config="$tmp_dir/curl.conf"
payload="$tmp_dir/payload.json"
response="$tmp_dir/response.json"

cat >"$config" <<EOF
silent
show-error
connect-timeout = 10
max-time = 30
url = "https://api.zeabur.com/graphql"
header = "Authorization: Bearer $ZEABUR_TOKEN"
header = "Content-Type: application/json"
output = "$response"
EOF
chmod 600 "$config"

jq -cn --arg projectID "$project_id" '{
  query: "query InspectProject($projectID: ObjectID!) { environments(projectID: $projectID) { _id name } services(projectID: $projectID) { edges { node { _id name } } } }",
  variables: {projectID: $projectID}
}' >"$payload"

curl --config "$config" --data-binary "@$payload"

if jq -e '.errors and (.errors | length > 0)' >/dev/null <"$response"; then
  jq -c '{errors}' <"$response" >&2
  exit 1
fi

jq --arg projectId "$project_id" '{
  projectId: $projectId,
  environments: (.data.environments // []),
  services: [(.data.services.edges // [])[].node]
}' <"$response"
