import { z } from 'zod'

import { objectIdSchema, planNumberSchema } from './shared'

const databaseChangeStatusSchema = z.enum([
  'draft',
  'pending_approval',
  'approved',
  'executing',
  'succeeded',
  'failed',
  'rejected',
  'canceled',
  'expired',
])

export const databaseChangeRequestResponseSchema = z.object({
  id: z.union([objectIdSchema, planNumberSchema]),
  planId: planNumberSchema.optional(),
  proposalSource: z.enum(['human', 'agent']).optional(),
  sourceConversationId: z.string().optional(),
  kind: z.enum(['dml', 'ddl']),
  operation: z.enum([
    'insertOne',
    'insertMany',
    'updateOne',
    'updateMany',
    'deleteOne',
    'deleteMany',
    'createCollection',
    'dropCollection',
    'createIndex',
    'dropIndex',
  ]),
  database: z.string(),
  collection: z.string(),
  title: z.string(),
  description: z.string(),
  risk: z.string(),
  rollbackPlan: z.string(),
  statementDigest: z.string(),
  statementPreview: z.string(),
  statementPreviewTruncated: z.boolean(),
  statementRedactedFields: z.array(z.string()),
  requesterUserId: z.string(),
  authorizedExecutorUserIds: z.array(z.string()),
  approvals: z.array(
    z.object({
      userId: z.string(),
      comment: z.string().nullable(),
      createdAt: z.string().datetime(),
    }),
  ),
  requiredApprovals: z.number().int().nonnegative(),
  currentApprovals: z.number().int().nonnegative(),
  policyVersion: z.number().int().nonnegative(),
  status: databaseChangeStatusSchema,
  canEdit: z.boolean(),
  canApprove: z.boolean(),
  canReject: z.boolean(),
  canCancel: z.boolean(),
  canExecute: z.boolean(),
  expiresAt: z.string().datetime().nullable(),
  executionId: z.string().nullable(),
  executionStartedAt: z.string().datetime().nullable(),
  executionCompletedAt: z.string().datetime().nullable(),
  executionResult: z.record(z.unknown()).nullable(),
  executionErrorCategory: z
    .enum([
      'dns',
      'route',
      'tls',
      'authentication',
      'authorization',
      'database-unavailable',
      'unknown',
    ])
    .nullable(),
  executionErrorMessage: z.string().nullable(),
  events: z.array(
    z.object({
      type: z.enum([
        'created',
        'updated',
        'submitted',
        'approved',
        'rejected',
        'canceled',
        'expired',
        'execution_started',
        'execution_succeeded',
        'execution_failed',
        'policy_invalidated',
      ]),
      actorUserId: z.string(),
      at: z.string().datetime(),
      comment: z.string().nullable(),
    }),
  ),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})
