import { z } from 'zod'

import {
  databaseConnectionCreateSchema,
  databaseConnectionTestSchema,
  databaseConnectionUpdateSchema,
} from './connection-schemas'
import {
  databaseCatalogCollectionQuerySchema,
  databaseCatalogCollectionsQuerySchema,
  databaseCatalogQuerySchema,
  databaseMongoReadQuerySchema,
  databaseQueryAuditListSchema,
} from './request-schemas'
import {
  databaseCatalogResponseSchema,
  databaseCollectionDetailResponseSchema,
  databaseCollectionsResponseSchema,
  databaseConnectionResponseSchema,
  databaseQueryAuditSchema,
  databaseQueryResultSchema,
  testResponseSchema,
} from './response-schemas'
import { connectionPathSchema, teamPathSchema } from './shared'

import type { ApiOperation } from '../registry'

export const databaseConnectionCoreOperations = [
  {
    operationId: 'databaseConnections.list',
    method: 'get',
    path: '/teams/{teamId}/database-connections',
    tags: ['Databases'],
    summary: 'List database connections',
    description:
      'Lists database connections visible to the team member. Credentials are never returned.',
    auth: 'bearer',
    pathSchema: teamPathSchema,
    responseSchema: z.object({ connections: z.array(databaseConnectionResponseSchema) }),
  },
  {
    operationId: 'databaseConnections.create',
    method: 'post',
    path: '/teams/{teamId}/database-connections',
    tags: ['Databases'],
    summary: 'Create a database connection',
    description: 'Tests and stores an encrypted MongoDB or PostgreSQL connection.',
    auth: 'bearer',
    pathSchema: teamPathSchema,
    requestSchema: databaseConnectionCreateSchema,
    responseSchema: databaseConnectionResponseSchema,
  },
  {
    operationId: 'databaseConnections.testInput',
    method: 'post',
    path: '/teams/{teamId}/database-connections/test',
    tags: ['Databases'],
    summary: 'Test database credentials',
    description: 'Tests credentials without persisting or returning the connection URI.',
    auth: 'bearer',
    pathSchema: teamPathSchema,
    requestSchema: databaseConnectionTestSchema,
    responseSchema: testResponseSchema,
  },
  {
    operationId: 'databaseConnections.get',
    method: 'get',
    path: '/teams/{teamId}/database-connections/{connectionId}',
    tags: ['Databases'],
    summary: 'Get a database connection',
    description: 'Returns redacted database metadata only.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    responseSchema: databaseConnectionResponseSchema,
  },
  {
    operationId: 'databaseConnections.update',
    method: 'patch',
    path: '/teams/{teamId}/database-connections/{connectionId}',
    tags: ['Databases'],
    summary: 'Update a database connection',
    description: 'Updates metadata, policy, or tested encrypted credentials.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    requestSchema: databaseConnectionUpdateSchema,
    responseSchema: databaseConnectionResponseSchema,
  },
  {
    operationId: 'databaseConnections.delete',
    method: 'delete',
    path: '/teams/{teamId}/database-connections/{connectionId}',
    tags: ['Databases'],
    summary: 'Delete a database connection',
    description: 'Permanently deletes a database connection and its encrypted credential.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    responseSchema: z.object({ ok: z.literal(true) }),
  },
  {
    operationId: 'databaseConnections.testStored',
    method: 'post',
    path: '/teams/{teamId}/database-connections/{connectionId}/test',
    tags: ['Databases'],
    summary: 'Test a stored database connection',
    description:
      'Decrypts only on the backend, runs a health check, and persists the redacted result.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    requestSchema: z.object({}).strict(),
    responseSchema: databaseConnectionResponseSchema,
  },
  {
    operationId: 'databaseConnections.catalog',
    method: 'get',
    path: '/teams/{teamId}/database-connections/{connectionId}/catalog',
    tags: ['Databases'],
    summary: 'List MongoDB databases',
    description: 'Lists authorized MongoDB databases through the backend credential boundary.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    querySchema: databaseCatalogQuerySchema,
    responseSchema: databaseCatalogResponseSchema,
  },
  {
    operationId: 'databaseConnections.collections',
    method: 'get',
    path: '/teams/{teamId}/database-connections/{connectionId}/catalog/collections',
    tags: ['Databases'],
    summary: 'List MongoDB collections',
    description: 'Lists collections and bounded statistics for one authorized database.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    querySchema: databaseCatalogCollectionsQuerySchema,
    responseSchema: databaseCollectionsResponseSchema,
  },
  {
    operationId: 'databaseConnections.collectionDetail',
    method: 'get',
    path: '/teams/{teamId}/database-connections/{connectionId}/catalog/collection',
    tags: ['Databases'],
    summary: 'Describe a MongoDB collection',
    description: 'Returns indexes, validation metadata, and a bounded value-free schema sample.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    querySchema: databaseCatalogCollectionQuerySchema,
    responseSchema: databaseCollectionDetailResponseSchema,
  },
  {
    operationId: 'databaseConnections.queryMongo',
    method: 'post',
    path: '/teams/{teamId}/database-connections/{connectionId}/query/mongodb',
    tags: ['Databases'],
    summary: 'Run a bounded MongoDB read query',
    description:
      'Executes an allowlisted read operation through the audited backend gateway. Credentials and raw database errors are never returned.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    requestSchema: databaseMongoReadQuerySchema,
    responseSchema: databaseQueryResultSchema,
  },
  {
    operationId: 'databaseConnections.queryAudit',
    method: 'get',
    path: '/teams/{teamId}/database-connections/{connectionId}/query/audit',
    tags: ['Databases'],
    summary: 'List database query audit events',
    description:
      'Returns query audit metadata with a bounded, sanitized statement. Raw request bodies, sensitive query values, result values, and credentials are never stored.',
    auth: 'bearer',
    pathSchema: connectionPathSchema,
    querySchema: databaseQueryAuditListSchema,
    responseSchema: z.object({ events: z.array(databaseQueryAuditSchema) }),
  },
] satisfies readonly ApiOperation[]
