export function persistentCredentialCommand(clusterName: string): string {
  // On-prem connectors back the complete Kubernetes console, including exec, port-forward,
  // workload mutations and node terminals. A view-only binding leaves those product paths broken.
  return [
    `kubectl create namespace nuphos-relay --dry-run=client -o yaml | kubectl apply -f -`,
    `kubectl create serviceaccount nuphos -n nuphos-relay --dry-run=client -o yaml | kubectl apply -f -`,
    `kubectl create clusterrolebinding nuphos-cluster-admin \\`,
    `  --clusterrole=cluster-admin --serviceaccount=nuphos-relay:nuphos \\`,
    `  --dry-run=client -o yaml | kubectl apply -f -`,
    `kubectl apply -f - <<'TOKEN_EOF'`,
    `apiVersion: v1`,
    `kind: Secret`,
    `metadata:`,
    `  name: nuphos-console-token`,
    `  namespace: nuphos-relay`,
    `  annotations:`,
    `    kubernetes.io/service-account.name: nuphos`,
    `type: kubernetes.io/service-account-token`,
    `TOKEN_EOF`,
    `for _ in $(seq 1 30); do`,
    `  TOKEN=$(kubectl -n nuphos-relay get secret nuphos-console-token -o go-template='{{if .data}}{{.data.token | base64decode}}{{end}}')`,
    `  [ -n "\${TOKEN}" ] && break`,
    `  sleep 1`,
    `done`,
    `[ -n "\${TOKEN}" ] || { echo "ServiceAccount token was not issued" >&2; exit 1; }`,
    `CA=$(kubectl -n nuphos-relay get configmap kube-root-ca.crt -o go-template='{{index .data "ca.crt"}}' | base64 | tr -d '\\n')`,
    `cat <<KUBECONFIG_EOF`,
    `apiVersion: v1`,
    `kind: Config`,
    `clusters:`,
    `- name: ${clusterName}`,
    `  cluster:`,
    `    server: https://kubernetes.default.svc`,
    `    certificate-authority-data: \${CA}`,
    `contexts:`,
    `- name: ${clusterName}`,
    `  context:`,
    `    cluster: ${clusterName}`,
    `    user: nuphos`,
    `current-context: ${clusterName}`,
    `users:`,
    `- name: nuphos`,
    `  user:`,
    `    token: \${TOKEN}`,
    `KUBECONFIG_EOF`,
  ].join('\n')
}
