/* eslint-disable max-lines -- Generated copy of Cloudflare's OAuth scope catalog; one list is easier to diff against the API than split files. */
// Every OAuth scope Cloudflare offers, grouped by Cloudflare's own scope
// categories. Generated from `GET https://api.cloudflare.com/client/v4/oauth/scopes`;
// regenerate when Cloudflare adds scopes. The Nuphos OAuth client must be
// registered with every scope listed here, or Cloudflare rejects the authorize
// request.
import {
  faBolt,
  faChartLine,
  faEllipsis,
  faEnvelope,
  faGauge,
  faGlobe,
  faNetworkWired,
  faPhotoFilm,
  faRobot,
  faShieldHalved,
  faSliders,
  faUser,
  faUserShield,
} from '@fortawesome/free-solid-svg-icons'

export const CLOUDFLARE_SCOPE_CATEGORIES = [
  {
    key: 'dns_and_zones',
    label: 'DNS & zones',
    hint: 'Zones, records, registrar',
    icon: faGlobe,
    scopes: [
      'account-dns-settings.read',
      'account-dns-settings.write',
      'dns-firewall.read',
      'dns-firewall.write',
      'dns.read',
      'dns-view.read',
      'dns-view.write',
      'dns.write',
      'registrar-domains.admin',
      'registrar-domains.read',
      'registrar-sandbox-domains.admin',
      'registrar-sandbox-domains.read',
      'zone-custom-asset.read',
      'zone-custom-asset.write',
      'zone-dns-settings.read',
      'zone-dns-settings.write',
      'zone.read',
      'zone-settings.read',
      'zone-settings.write',
      'zone-versioning.read',
      'zone-versioning.write',
      'zone.write',
    ],
  },
  {
    key: 'developer_platform',
    label: 'Developer platform',
    hint: 'Workers, Containers, Pages, R2, D1, KV, Queues',
    icon: faBolt,
    scopes: [
      'agent-memory.write',
      'browser-rendering.read',
      'browser-rendering.write',
      'cf-agents.read',
      'cf-agents.write',
      'cloud-connector.read',
      'cloud-connector.write',
      'cloudchamber.read',
      'cloudchamber.write',
      'constellation.read',
      'constellation.write',
      'd1.metadata_read',
      'd1.read',
      'd1.write',
      'flagship.evaluate',
      'flagship.read',
      'flagship.write',
      'query-cache.read',
      'query-cache.write',
      'k2.read',
      'k2.write',
      'k2.consume',
      'k2.produce',
      'mcp-portals.read',
      'mcp-portals.write',
      'messaging.edit',
      'messaging.metadata_read',
      'messaging.read',
      'cfspeed.read',
      'cfspeed.write',
      'pages.metadata_read',
      'page.read',
      'page.write',
      'pipelines.read',
      'pipelines.send',
      'pipelines.write',
      'pubsub.read',
      'pubsub.write',
      'queues.metadata_read',
      'queues.read',
      'queues.write',
      'realtime.write',
      'realtime.admin',
      'realtime.read',
      'secrets-store.read',
      'secrets-store.write',
      'vectorize.read',
      'vectorize.write',
      'workers-ci.read',
      'workers-ci.write',
      'containers.read',
      'containers.write',
      'workers-scripts.edit',
      'workers-kv-storage.metadata_read',
      'workers-kv-storage.read',
      'workers-kv-storage.write',
      'workers-scripts.metadata_read',
      'workers-observability.read',
      'workers-observability-telemetry.write',
      'workers-observability.write',
      'r2-catalog.read',
      'r2-catalog.write',
      'r2-catalog-sql.read',
      'workers-r2-bucket-item.read',
      'workers-r2-bucket-item.write',
      'workers-r2.metadata_read',
      'workers-r2.read',
      'workers-r2.write',
      'workers-routes.read',
      'workers-routes.write',
      'workers-scripts.read',
      'workers-scripts.write',
      'workers-tail.read',
    ],
  },
  {
    key: 'ai_and_machine_learning',
    label: 'AI',
    hint: 'Workers AI, AI Gateway, AI Search',
    icon: faRobot,
    scopes: [
      'aiaudit.read',
      'aiaudit.write',
      'aig.metadata_read',
      'aig.read',
      'aig.run',
      'aig.write',
      'ai-search.index',
      'ai-search.metadata_read',
      'ai-search.read',
      'ai-search.run',
      'ai-search.write',
      'agw.read',
      'agw.run',
      'agw.write',
      'rag.read',
      'rag.write',
      'rag.run',
      'firewall-for-ai.read',
      'firewall-for-ai.write',
      'websearch.metadata_read',
      'websearch.read',
      'websearch.run',
      'websearch.write',
      'ai-model.read',
      'ai-model.write',
      'workers_ai.metadata_read',
      'ai.read',
      'ai.write',
    ],
  },
  {
    key: 'analytics_and_logs',
    label: 'Analytics & logs',
    hint: 'Analytics, Logpush, Radar',
    icon: faChartLine,
    scopes: [
      'account-analytics.read',
      'analytics.read',
      'intel.read',
      'intel.write',
      'account-logs.read',
      'logs.read',
      'account-logs.write',
      'logs.write',
      'radar.read',
      'zone-observability.read',
      'zone-observability.write',
    ],
  },
  {
    key: 'app_security',
    label: 'Application security',
    hint: 'WAF, bots, DDoS, Page Shield',
    icon: faShieldHalved,
    scopes: [
      'fraud-detection-pii.read',
      'account-firewall-access-rules.read',
      'account-firewall-access-rules.write',
      'account-security-center-insights.read',
      'account-security-center-insights.write',
      'account-waf.read',
      'account-waf.write',
      'request-tracer.read',
      'reports-application-security-report.read',
      'bot-management-feedback.read',
      'bot-management-feedback.write',
      'bot-management.read',
      'bot-management.write',
      'cloudforce-one.read',
      'cloudforce-one.write',
      'ddos-botnet-feed.read',
      'ddos-botnet-feed.write',
      'ddos-protection.read',
      'ddos-protection.write',
      'api-gateway.write',
      'api-gateway.read',
      'domain-page.shield',
      'domain-page-shield.read',
      'field-extractor.read',
      'field-extractor.write',
      'firewall-services.read',
      'firewall-services.write',
      'fraud-detection.read',
      'fraud-detection.write',
      'fraud-events.write',
      'fraud-feedback.read',
      'fraud-feedback.write',
      'http-applications.read',
      'http-applications.write',
      'http-ddos-managed-ruleset.read',
      'http-ddos-managed-ruleset.write',
      'iot.read',
      'iot.write',
      'l4-ddos-managed-ruleset.read',
      'l4-ddos-managed-ruleset.write',
      'page-rules.read',
      'page-rules.write',
      'page.shield',
      'page-shield.read',
      'precursor.read',
      'precursor.write',
      'sanitize.read',
      'sanitize.write',
      'tag.read',
      'tag.write',
      'trust-and-safety.read',
      'trust-and-safety.write',
      'challenge-widgets.read',
      'challenge-widgets.write',
      'url-scanner.read',
      'url-scanner.write',
      'zaraz.write',
      'zaraz.edit',
      'zaraz.read',
      'zone-security-center-insights.read',
      'zone-security-center-insights.write',
      'zone-waf.read',
      'zone-waf.write',
    ],
  },
  {
    key: 'cache_and_performance',
    label: 'Cache & SSL',
    hint: 'Cache settings, purge, certificates',
    icon: faGauge,
    scopes: [
      'account-ssl-and-certificates.read',
      'account-ssl-and-certificates.write',
      'cache.purge',
      'cache-settings.read',
      'cache-settings.write',
      'account-disable-esc.read',
      'zone-disable-esc.read',
      'account-disable-esc.write',
      'zone-disable-esc.write',
      'ssl-and-certificates.read',
      'ssl-and-certificates.write',
    ],
  },
  {
    key: 'cloudflare_one_and_zero_trust',
    label: 'Zero Trust',
    hint: 'Access, Gateway, Tunnels, WARP',
    icon: faUserShield,
    scopes: [
      'access-app.read',
      'access-app.revoke',
      'access-app.write',
      'access.read',
      'zone-access.read',
      'access.revoke',
      'zone-access.revoke',
      'access.write',
      'zone-access.write',
      'access-audit-log.read',
      'access-custom-page.read',
      'access-custom-page.write',
      'access-device-posture.read',
      'access-device-posture.write',
      'access-group.read',
      'access-group.write',
      'access-idp.read',
      'access-idp.write',
      'access-key.read',
      'access-key.write',
      'access-certificate.read',
      'access-certificate.write',
      'access-org.read',
      'access-org.revoke',
      'access-org.write',
      'access-acct.read',
      'access-acct.revoke',
      'access-acct.write',
      'access-policy.read',
      'access-policy.write',
      'access-policy-test.read',
      'access-policy-test.write',
      'access-saml-certificate.read',
      'access-saml-certificate.write',
      'access-scim-log.read',
      'access-population.read',
      'access-population.write',
      'access-ssh-auditing.read',
      'access-ssh-auditing.write',
      'access-service-token.read',
      'access-service-token.write',
      'access-tag.read',
      'access-tag.write',
      'access-users.read',
      'access-users.write',
      'casb.read',
      'casb.write',
      'teams-cds-compute-account.read',
      'teams-cds-compute-account.write',
      'teams-dex.read',
      'teams-dex.write',
      'teams-connector-cloudflared.monitoring',
      'teams-connector-warp.read',
      'teams-connector-warp.write',
      'teams-connector-cloudflared.read',
      'teams-connector-cloudflared.write',
      'teams-connectors.read',
      'teams-connectors.write',
      'teams-networks.read',
      'teams-networks.write',
      'argotunnel.read',
      'argotunnel.write',
      'teams-secure.location',
      'dls.read',
      'dls.write',
      'resource-library.read',
      'resource-library.write',
      'teams.read',
      'teams.report',
      'teams-resilience.read',
      'teams-resilience.write',
      'teams.write',
      'teams-pii.read',
      'access-seats.write',
    ],
  },
  {
    key: 'email_and_messaging',
    label: 'Email',
    hint: 'Email Routing, Email Security, sending',
    icon: faEnvelope,
    scopes: [
      'cloud-email-security.read',
      'cloud-email-security.write',
      'email-routing-account-rule.read',
      'email-routing-address.read',
      'email-routing-address.write',
      'email-routing-rule.read',
      'email-routing-rule.write',
      'email-routing-suppression.read',
      'email-routing-suppression.write',
      'email-security-dmarcreports.read',
      'email-security-dmarcreports.write',
      'email-sending.read',
      'email-sending.write',
    ],
  },
  {
    key: 'media',
    label: 'Media',
    hint: 'Images, Stream, Calls',
    icon: faPhotoFilm,
    scopes: [
      'calls.read',
      'calls.write',
      'images.metadata_read',
      'images.read',
      'images.write',
      'moq.read',
      'moq.write',
      'stream.metadata_read',
      'stream.read',
      'stream.write',
    ],
  },
  {
    key: 'network_services',
    label: 'Network services',
    hint: 'Load balancing, Magic Transit/WAN, IP prefixes',
    icon: faNetworkWired,
    scopes: [
      'account-waiting-rooms.read',
      'address-maps.read',
      'address-maps.write',
      'chinanetwork-steering.read',
      'chinanetwork-steering.write',
      'connectivity-directory.admin',
      'connectivity-directory.bind',
      'connectivity-directory.read',
      'healthcheck.read',
      'healthcheck.write',
      'ip-prefix-bgp-on-demand.read',
      'ip-prefix-bgp-on-demand.write',
      'ip-prefix.read',
      'ip-prefix.write',
      'load-balancers-account.read',
      'load-balancers-account.write',
      'load-balancers.read',
      'load-balancers.write',
      'load-balancing-monitors-and-pools.read',
      'load-balancing-monitors-and-pools.write',
      'pcaps-api.read',
      'pcaps-api.write',
      'magic-firewall.read',
      'magic-firewall.write',
      'fbm.admin',
      'fbm.read',
      'fbm.write',
      'magic-transit.read',
      'magic-transit.write',
      'magic-wan.read',
      'magic-wan.write',
      'waiting-rooms.read',
      'waiting-rooms.write',
      'web3-hostnames.read',
      'web3-hostnames.write',
    ],
  },
  {
    key: 'rules_and_configuration',
    label: 'Rules & configuration',
    hint: 'Rulesets, redirects, transforms, custom pages',
    icon: faSliders,
    scopes: [
      'account-custom-error-rules.read',
      'account-custom-error-rules.write',
      'account-custom-pages.read',
      'account-custom-pages.write',
      'account-rule-lists.read',
      'account-rule-lists.write',
      'account-rulesets.read',
      'account-rulesets.write',
      'config-settings.read',
      'config-settings.write',
      'custom-errors.read',
      'custom-errors.write',
      'custom-pages.read',
      'custom-pages.write',
      'dynamic-redirect.read',
      'dynamic-redirect.write',
      'managed-headers.read',
      'managed-headers.write',
      'mass-url-redirects.read',
      'mass-url-redirects.write',
      'origin.read',
      'origin.write',
      'payments-gateway.read',
      'payments-gateway.write',
      'response-compression.read',
      'response-compression.write',
      'select-configuration.read',
      'select-configuration.write',
      'snippets.read',
      'snippets.write',
      'transform-rules.read',
      'transform-rules.write',
      'zone-transform-rules.read',
      'zone-transform-rules.write',
    ],
  },
  {
    key: 'account_and_billing',
    label: 'Account',
    hint: 'Settings, members, API tokens, notifications',
    icon: faUser,
    scopes: [
      'account-api-gateway.write',
      'account-api-gateway.read',
      'account-api-tokens.write',
      'account-custom-asset.read',
      'account-custom-asset.write',
      'account-settings.read',
      'account-settings.write',
      'apps.write',
      'integration.write',
      'memberships.read',
      'memberships.write',
      'notifications.read',
      'notifications.write',
      'scim-provisioning.write',
      'user-details.read',
      'user-details.write',
    ],
  },
  {
    key: 'other',
    label: 'Other',
    hint: 'Artifacts, resource sharing',
    icon: faEllipsis,
    scopes: ['artifacts.read', 'artifacts.write', 'resource-sharing.read'],
  },
] as const
