import * as atlas from '../atlas'

export const cloudInfraChannels = {
  'atlas:listAwsVpcs': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    roleId?: string,
  ) => atlas.listAwsVpcs(teamId, accountId, region, roleId),
  'atlas:listAwsNacls': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    vpcId?: string,
    roleId?: string,
  ) => atlas.listAwsNacls(teamId, accountId, { region, vpcId, roleId }),
  'atlas:listAwsClusters': (_e: unknown, teamId: string, accountId: string, roleId?: string) =>
    atlas.listAwsClusters(teamId, accountId, roleId),
  'atlas:getAwsIamPermissions': (_e: unknown, teamId: string, accountId: string, roleId?: string) =>
    atlas.getAwsIamPermissions(teamId, accountId, roleId),
  'atlas:listPermissionGrantProposals': (_e: unknown, teamId: string) =>
    atlas.listPermissionGrantProposals(teamId),
  'atlas:getPermissionGrantProposal': (_e: unknown, teamId: string, id: string) =>
    atlas.getPermissionGrantProposal(teamId, id),
  'atlas:approvePermissionGrantProposal': (_e: unknown, teamId: string, id: string) =>
    atlas.approvePermissionGrantProposal(teamId, id),
  'atlas:rejectPermissionGrantProposal': (_e: unknown, teamId: string, id: string) =>
    atlas.rejectPermissionGrantProposal(teamId, id),
  'atlas:getGcpIamPermissions': (
    _e: unknown,
    teamId: string,
    projectId: string,
    serviceAccountId?: string,
  ) => atlas.getGcpIamPermissions(teamId, projectId, serviceAccountId),
  'atlas:getCloudflareIamPermissions': (_e: unknown, teamId: string, accountId: string) =>
    atlas.getCloudflareIamPermissions(teamId, accountId),
  'atlas:listGcpVpcs': (
    _e: unknown,
    teamId: string,
    projectId: string,
    serviceAccountId?: string,
  ) => atlas.listGcpVpcs(teamId, projectId, serviceAccountId),
  'atlas:listGcpFirewalls': (
    _e: unknown,
    teamId: string,
    projectId: string,
    serviceAccountId?: string,
  ) => atlas.listGcpFirewalls(teamId, projectId, serviceAccountId),
  'atlas:listGcpClusters': (
    _e: unknown,
    teamId: string,
    projectId: string,
    serviceAccountId?: string,
  ) => atlas.listGcpClusters(teamId, projectId, serviceAccountId),
  'atlas:listAwsEc2Instances': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    roleId?: string,
  ) => atlas.listAwsEc2Instances(teamId, accountId, region, roleId),
  'atlas:listAwsEcsClusters': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    roleId?: string,
  ) => atlas.listAwsEcsClusters(teamId, accountId, region, roleId),
  'atlas:listAwsEcsServices': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    clusterName: string,
    roleId?: string,
  ) => atlas.listAwsEcsServices(teamId, accountId, region, clusterName, roleId),
  'atlas:listAwsEcsTasks': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    clusterName: string,
    desiredStatus?: 'RUNNING' | 'STOPPED',
    roleId?: string,
  ) => atlas.listAwsEcsTasks(teamId, accountId, region, clusterName, desiredStatus, roleId),
  'atlas:listAwsEcsContainerInstances': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    clusterName: string,
    roleId?: string,
  ) => atlas.listAwsEcsContainerInstances(teamId, accountId, region, clusterName, roleId),
  'atlas:getAwsEcsClusterMetrics': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    clusterName: string,
    rangeMinutes?: number,
    roleId?: string,
  ) => atlas.getAwsEcsClusterMetrics(teamId, accountId, region, clusterName, rangeMinutes, roleId),
  'atlas:listAwsCfnStacks': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    roleId?: string,
  ) => atlas.listAwsCfnStacks(teamId, accountId, region, roleId),
  'atlas:listAwsS3Buckets': (_e: unknown, teamId: string, accountId: string, roleId?: string) =>
    atlas.listAwsS3Buckets(teamId, accountId, roleId),
  'atlas:listAwsS3BucketObjects': (
    _e: unknown,
    teamId: string,
    accountId: string,
    bucket: string,
    region: string,
    prefix: string,
    continuationToken: string | null,
    roleId?: string,
  ) =>
    atlas.listAwsS3BucketObjects(
      teamId,
      accountId,
      bucket,
      region,
      prefix,
      continuationToken,
      roleId,
    ),
  'atlas:getAwsS3ObjectDownloadUrl': (
    _e: unknown,
    teamId: string,
    accountId: string,
    bucket: string,
    region: string,
    key: string,
    roleId?: string,
  ) => atlas.getAwsS3ObjectDownloadUrl(teamId, accountId, bucket, region, key, roleId),
  'atlas:getAwsS3ObjectPreview': (
    _e: unknown,
    teamId: string,
    accountId: string,
    bucket: string,
    region: string,
    key: string,
    roleId?: string,
  ) => atlas.getAwsS3ObjectPreview(teamId, accountId, bucket, region, key, roleId),
  'atlas:listAwsLambdaFunctions': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    roleId?: string,
  ) => atlas.listAwsLambdaFunctions(teamId, accountId, region, roleId),
  'atlas:getAwsLambdaFunctionDetail': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    name: string,
    roleId?: string,
  ) => atlas.getAwsLambdaFunctionDetail(teamId, accountId, region, name, roleId),
  'atlas:getAwsLambdaFunctionMetrics': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    name: string,
    rangeMinutes?: number,
    roleId?: string,
  ) => atlas.getAwsLambdaFunctionMetrics(teamId, accountId, region, name, rangeMinutes, roleId),
  'atlas:listAwsCloudWatchAlarms': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region?: string,
    roleId?: string,
  ) => atlas.listAwsCloudWatchAlarms(teamId, accountId, region, roleId),
  'atlas:invokeAwsLambdaFunction': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    name: string,
    payload: string,
    roleId?: string,
  ) => atlas.invokeAwsLambdaFunction(teamId, accountId, region, name, payload, roleId),
  'atlas:updateAwsLambdaFunctionConfig': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    name: string,
    updates: { memoryMb?: number; timeoutSec?: number; environment?: Record<string, string> },
    roleId?: string,
  ) => atlas.updateAwsLambdaFunctionConfig(teamId, accountId, region, name, updates, roleId),
  'atlas:getAwsLambdaTriggers': (
    _e: unknown,
    teamId: string,
    accountId: string,
    region: string,
    name: string,
    roleId?: string,
  ) => atlas.getAwsLambdaTriggers(teamId, accountId, region, name, roleId),
} as const
